export const DELETE_RECIPE = 'DELETE_RECIPE'
export const ADD_RECIPE = 'ADD_RECIPE'
export const DELETE_ALL = 'DELETE_ALL'
export const SEARCH_RECIPE = 'SEARCH_RECIPE'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_RECIPE_FROM_CART = 'REMOVE_RECIPE_FROM_CART'

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const LOAD_PRODUCT_DETAILS = 'LOAD_PRODUCT_DETAILS';

export const LOAD_INGREDIENTS = 'LOAD_INGREDIENTS';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';


export const LOAD_ORDER = 'LOAD_ORDER';
export const ADD_ORDER_ITEM = 'ADD_ORDER_ITEM';
export const REMOVE_ORDER_ITEM = 'REMOVE_ORDER_ITEM';
export const TOGGLE_ORDER_STATUS_MENU = 'TOGGLE_ORDER_STATUS_MENU';